version: "3"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./src/tmp/db:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: ./.env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    depends_on:
      - db

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
